apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pythoughts

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"

images:
  - name: pythoughts/api
    newTag: latest
  - name: pythoughts/worker
    newTag: latest
